# Generated by Django 3.0.5 on 2021-04-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=3)),
                ('altura', models.CharField(max_length=10)),
                ('valor', models.IntegerField()),
                ('goles', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('amarillas', models.IntegerField()),
                ('segundas_amarillas', models.IntegerField()),
                ('rojas', models.IntegerField()),
                ('tiempo_juego', models.IntegerField()),
                ('victorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('ausencias', models.IntegerField()),
            ],
        ),
    ]
