# Generated by Django 3.0.5 on 2021-04-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='foto',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
